name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/
      
    - name: Set environment variables
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "echo 'DB_ENDPOINT=${{ secrets.DB_ENDPOINT }}' >> /etc/environment"

